-- DROP TABLE IF EXISTS P_USER;
-- DROP TABLE IF EXISTS USER;
--
-- DROP TABLE IF EXISTS P_MULTIPLICATION_RESULT_ATTEMPT;
-- DROP TABLE IF EXISTS MULTIPLICATION_RESULT_ATTEMPT;
--
-- DROP TABLE IF EXISTS P_MULTIPLICATION;
-- DROP TABLE IF EXISTS MULTIPLICATION;

-- CREATE TABLE IF NOT EXISTS P_USER (
--     USER_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
--     ALIAS VARCHAR(50)
-- );

-- CREATE TABLE IF NOT EXISTS P_MULTIPLICATION_RESULT_ATTEMPT (
--     ID INTEGER PRIMARY KEY AUTO_INCREMENT,
--     CORRECT BOOLEAN,
--     RESULT_ATTEMPT INT,
--     MULTIPLICATION_ID BIGINT NOT NULL,
--     USER_ID BIGINT NOT NULL
-- );

-- CREATE TABLE IF NOT EXISTS P_MULTIPLICATION (
--     MULTIPLICATION_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
--     FACTORA INT,
--     FACTORB INT
-- );